export {
  createProjectDocument,
  type CreateProjectDocumentInput,
} from "./document/factory.js";
export {
  ProjectDocumentParseError,
  parseProjectDocument,
  serializeProjectDocument,
  type ProjectDocumentParseErrorCode,
} from "./document/serialization.js";
export {
  CURRENT_PROJECT_DOCUMENT_SCHEMA_VERSION,
  type Clock,
  type IdFactory,
  type ProjectDocument,
  type ProjectDocumentSchemaVersion,
} from "./document/types.js";
export {
  classifierType,
  emptyCanonicalUmlModel,
  emptyDiagramLayout,
  multiplicity,
  primitiveType,
  type AggregationKind,
  type CanonicalUmlModel,
  type DiagramLayout,
  type DiagramNodeLayout,
  type PrimitiveTypeName,
  type UmlAssociation,
  type UmlAssociationEnd,
  type UmlAttribute,
  type UmlClass,
  type UmlClassifier,
  type UmlElementId,
  type UmlEnumeration,
  type UmlEnumerationLiteral,
  type UmlGeneralization,
  type UmlMultiplicity,
  type UmlOperation,
  type UmlPackage,
  type UmlParameter,
  type UmlTypeReference,
  type Visibility,
} from "./model/types.js";
export {
  emptyGenerationProfile,
  type AttributeGenerationProfile,
  type ClassGenerationProfile,
  type DefaultSortProfile,
  type GenerationProfile,
} from "./profile/types.js";
export {
  collectValidationDiagnostics,
  validateProjectDocument,
} from "./validation/validator.js";
export {
  type ValidationDiagnostic,
  type ValidationDiagnosticCode,
  type ValidationPolicy,
  type ValidationResult,
  type ValidationSeverity,
} from "./validation/types.js";
export {
  isUmlCommand,
} from "./commands/runtime-validation.js";
export { UmlCommandBus } from "./commands/bus.js";
export {
  type AcceptedUmlCommandResult,
  type AddAttributeCommand,
  type AddEnumerationLiteralCommand,
  type AddOperationCommand,
  type AddParameterCommand,
  type CreateAssociationCommand,
  type CreateClassCommand,
  type CreateEnumerationCommand,
  type CreateGeneralizationCommand,
  type CreatePackageCommand,
  type DeleteAssociationCommand,
  type DeleteClassCommand,
  type DeleteEnumerationCommand,
  type DeleteGeneralizationCommand,
  type DeletePackageCommand,
  type MoveNodeCommand,
  type RejectedUmlCommandResult,
  type RemoveAttributeCommand,
  type RemoveEnumerationLiteralCommand,
  type RemoveOperationCommand,
  type RemoveParameterCommand,
  type RenameClassCommand,
  type RenameEnumerationCommand,
  type RenamePackageCommand,
  type UmlCommand,
  type UmlCommandError,
  type UmlCommandKind,
  type UmlCommandPreconditionCode,
  type UmlCommandPreconditionError,
  type UmlCommandResult,
  type UmlHistoryResult,
  type UmlCommandValidationError,
  type UnsupportedUmlCommandError,
  type UpdateAssociationCommand,
  type UpdateAttributeCommand,
  type UpdateGenerationProfileCommand,
  type UpdateOperationCommand,
  type UpdateParameterCommand,
} from "./commands/types.js";
